loadstring(game:HttpGet("https://raw.githubusercontent.com/crookrtk/RHUB/main/clovr2020.lua"))()
wait(4)
loadstring(game:HttpGet("https://raw.githubusercontent.com/crookrtk/RHUB/main/clovrhatsreanim.lua"))()
wait(4)
loadstring(game:HttpGet("https://raw.githubusercontent.com/crookrtk/RHUB/main/clovr2020.lua"))()
